apiVersion: batch/v1beta1 #<-- Add beta1 to be v1beta1 
kind: CronJob #<-- Change this line
metadata:
  name: sleepy
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template: #<-- This and following lines space four to right
        spec:
          containers:
          - name: resting
            image: busybox
            command: ["/bin/sleep"]
            args: ["3"]
          restartPolicy: Never