apiVersion: v1
kind: Pod
metadata:
  name: service-test-client
spec:
  restartPolicy: Never
  containers:
  - name: test-client
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "sleep 1000000"]
    volumeMounts:
    - name: vol1
      mountPath: /pvc
  nodeSelector:
    kubernetes.io/hostname: gke-my-gke-cluster-my-node-pool-af833853-7lbx
  volumes:
  - name: vol1
    persistentVolumeClaim: 
      claimName: helloweb-disk
