apiVersion: v1
kind: Pod
metadata:
  name: chapter9
  namespace: default
spec:
  containers: 
  - image: busybox
    volumeMounts:
    - mountPath: /busy
      name: test
    name: busy
    command:
    - sleep
    - "3600"
  - image: busybox
    volumeMounts:
    - mountPath: /box
      name: test 
    name: box
    command:
    - sleep
    - "3600"
  volumes: 
  - name: test 
    emptyDir: {}