apiVersion: v1
kind: Pod
metadata:
  name: chapter9
  namespace: default
spec:
  containers: 
  - image: busybox
    volumeMounts:
    - mountPath: /busy
      name: test
    - mountPath: /password
      name: password
    name: busy
    command:
    - sleep
    - "3600"
  - image: busybox
    volumeMounts:
    - mountPath: /box
      name: test 
    name: box
    command:
    - sleep
    - "3600"
    env:
    - name: MYPASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
  volumes: 
  - name: test 
    persistentVolumeClaim: 
      claimName: myclaim
  - name: password
    secret:
      secretName: mysql