kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: production
  name: dev-prod
rules:
- apiGroups: ["", "extentions"  , "apps"]
  resources: ["deployments","replicasets","pods" ]
  verbs: [ "get", "list", "watch" ]